services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: frank
      POSTGRES_PASSWORD: legacy_password
      POSTGRES_DB: hss_manager
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data