services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: hss_admin
      POSTGRES_PASSWORD: stark_secure_password
      POSTGRES_DB: hss_database
    ports:
      - "5432:5432" # Exposes DB to your host machine at localhost:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hss_admin -d hss_database"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: